version: '3.8'
name: 'users'
services:
  app:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./api:/api
      - ./logs:/logs
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:$PORT_HTTP:$PORT_HTTP"
      - "127.0.0.1:$PORT_GRPC:$PORT_GRPC"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-users}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:

