openapi: 3.0.3
info:
  title: Users
  description: Microservice enabling user management
  version: 1.0.0

servers:
  - url: http://localhost:8080/
    variables:
      hostname:
        default: localhost
security:
  - basicAuth: [ ]

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

                properties:
                  status:
                    type: string
                    example: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      operationId: getUsers
      summary: Fetches a paginated list of users, allowing to filter by a matching field
      parameters:
        - name: first_name
          in: query
          schema:
            type: string
          example: "Alice"
        - name: last_name
          in: query
          schema:
            type: string
          example: "Bob"
        - name: nickname
          in: query
          schema:
            type: string
          example: "AB123"
        - name: email
          in: query
          schema:
            type: string
            format: email
          example: "alice@bob.com"
        - name: country
          in: query
          schema:
            type: string
          example: "UK"
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 10
            description: Maximum number of records to return.
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
            description: Number of records to skip for pagination.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    post:
      summary: Create a new user
      requestBody:
        description: User object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUser'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{userID}:
    patch:
      summary: Update an existing user
      parameters:
        - in: path
          name: userID
          schema:
            type: string
          required: true
      requestBody:
        description: User object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete an existing user
      parameters:
        - in: path
          name: userID
          schema:
            type: string
          required: true
      responses:
        '204':
          description: No Content
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Users:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'

    Ok:
      type: object
      properties:
        status:
          type: string
          example: OK
      required:
        - status

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426655440000"
        first_name:
          type: string
          example: "Alice"
        last_name:
          type: string
          example: "Bob"
        nickname:
          type: string
          example: "AB123"
        email:
          type: string
          format: email
          example: "alice@bob.com"
        country:
          type: string
          example: "UK"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - first_name
        - last_name
        - nickname
        - email
        - country
        - created_at
        - updated_at

    PostUser:
      type: object
      properties:
        first_name:
          type: string
          example: "Alice"
        last_name:
          type: string
          example: "Bob"
        nickname:
          type: string
          example: "AB123"
        email:
          type: string
          format: email
          example: "alice@bob.com"
        country:
          type: string
          example: "UK"
        password:
          type: string
          format: password
          example: "password"
      required:
        - first_name
        - last_name
        - nickname
        - email
        - country
        - password

    PatchUser:
      type: object
      properties:
        first_name:
          type: string
          example: "Alice_modified"
        last_name:
          type: string
          example: "Bob_modified"
        nickname:
          type: string
          example: "AB123_modified"
        email:
          type: string
          format: email
          example: "alice_modified@bob.com"
        country:
          type: string
          example: "US"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: "Invalid input"


